name: classroom-autograding

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download JUnit Console
        run: |
          mkdir -p lib
          curl -L -o lib/junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar

      - name: Compile sources and tests
        run: |
          mkdir -p out
          javac -cp lib/junit-platform-console-standalone.jar -d out $(find src -name "*.java")

      - name: Run all tests
        run: |
          java -jar lib/junit-platform-console-standalone.jar -cp out --scan-classpath

      - name: Autograding
        uses: education/autograding@v1
